name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Show Test 3 Expected Output
      run: cat -e test_data/test3_expected.txt
    - name: Show Test 3 Actual Output
      run: cat -e test_data/actual3.txt
    - name: Test 3
      run: diff -q test_data/test3_expected.txt test_data/actual3.txt || (echo "Test 3 Failed" && exit 1)
