name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix
    - name: Produce Test 3 Output
      run: python find_lowest_number.py test_data/test3_input.txt test_data/actual3.txt
    - name: Normalize Line Endings
      run: |
        dos2unix test_data/test3_expected.txt
        dos2unix test_data/actual3.txt
    - name: Test 3
      run: diff test_data/test3_expected.txt test_data/actual3.txt
